name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

steps:
  - name: ⬇️ Checkout repo
    uses: actions/checkout@v3

  - name: 🧱 Install dependencies
    run: pnpm install

  - name: 🛠️ Build the app
    run: turbo run build
