name: Setup pnpm
description: Checks out repo and installs pnpm with proper PATH setup

runs:
  using: "composite"
  steps:
    - name: â¬‡ï¸ Checkout repo
      uses: actions/checkout@v3

    - name: ðŸ’¾ Install pnpm
      run: |
        npm install --global pnpm
        SHELL=bash pnpm setup
        pnpm config set global-bin-dir /home/runner/.pnpm-global/bin
        echo "/home/runner/.pnpm-global/bin" >> $GITHUB_PATH
      shell: bash
